#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: '3.7'
networks:
  dspacenet:
services:
  dspace:
    container_name: dspace
    depends_on:
      - dspacedb
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-5_x-jdk8-test}"
    environment:
      # Env vars with double underbars in names will be replaced with periods and written to dspace.cfg
      # The defaul values for dspace.cfg will be provided here
      # __D__ -> -
      # __P__ -> .
      - dspace__P__dir=/dspace
      - db__P__url=jdbc:postgresql://dspacedb:5432/dspace
      - dspace__P__hostname=localhost
      - dspace__P__baseUrl=http://localhost:8080
      - dspace__P__name=DSpace Started with Docker Compose
      - solr__P__server=http://localhost:8080/solr
    build:
      context: .
      dockerfile: Dockerfile.jdk8-test
    networks:
      dspacenet:
    ports:
      - published: 8080
        target: 8080
    stdin_open: true
    tty: true
    volumes:
      - ./dspace/src/main/docker-compose/xmlui.xconf:/dspace/config/xmlui.xconf
      - ./dspace/src/main/docker-compose/parse_configs.sh:/dspace/bin/parse_configs.sh
      - assetstore:/dspace/assetstore
      - solr_authority:/dspace/solr/authority/data
      - solr_oai:/dspace/solr/oai/data
      - solr_search:/dspace/solr/search/data
      - solr_statistics:/dspace/solr/statistics/data
  dspacedb:
    container_name: dspacedb
    environment:
      PGDATA: /pgdata
    image: dspace/dspace-postgres-pgcrypto
    networks:
      dspacenet:
    stdin_open: true
    tty: true
    volumes:
      - pgdata:/pgdata
volumes:
  assetstore:
  pgdata:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics: