#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: "3.7"

services:
  dspace-cli:
    image: "dspace/dspace-cli:${DSPACE_VER:-dspace-5_x}"
    container_name: dspace-cli
    build:
      context: .
      dockerfile: Dockerfile.cli.jdk8
    environment:
      # Env vars with double underbars in names will be replaced with periods and written to dspace.cfg
      # The defaul values for dspace.cfg will be provided here
      # __D__ -> -
      # __P__ -> .
      - dspace__P__dir=/dspace
      - db__P__url=jdbc:postgresql://dspacedb:5432/dspace
      - dspace__P__hostname=localhost
      - dspace__P__baseUrl=http://localhost:8080
      - dspace__P__name=DSpace Started with Docker Compose
      - solr__P__server=http://dspace:8080/solr
    volumes:
      - assetstore:/dspace/assetstore
    entrypoint: /dspace/bin/parse_env_to_configs.sh
    # Any commands passed here will be forwarded to /dspace/bin/dspace by parse_env_to_configs.sh (see its code)
    command: help
    networks:
      - dspacenet
    tty: true
    stdin_open: true

volumes:
  assetstore:

networks:
  dspacenet: