# Concepts borrowed from
# DSpace 5_x
name: Build

# Run this Build for all pushes / PRs to current branch
on: [push, pull_request]

jobs:
  build-and-test:
          runs-on: ubuntu-latest
          container: adoptopenjdk/maven-openjdk8:latest
          services:
                  # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
                  postgres:
                          image: postgres
                          env:
                                 POSTGRES_USER: dspace
                                 POSTGRES_PASSWORD: password
                                 POSTGRES_HOST_AUTH_METHOD: md5
                                 POSTGRES_INITDB_ARGS: --auth-host=md5
                          options: >-
                                --health-cmd pg_isready
                                --health-interval 10s
                                --health-timeout 5s
                                --health-retries 5
          env:
              MAVEN_OPTS: "-Xmx4g -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
          steps:
              - name: apt install
                run: |
                     apt-get update &&
                     apt-get install -y --no-install-recommends \
                             build-essential \
                             zlib1g-dev \
                             libssl-dev \
                             libxml2-dev \
                             curl \
                             wget \
                             postgresql-client \
                             libxml2-utils \
                             python \
                             unzip &&
                     apt-get download ant ant-optional &&
                     dpkg --force-all -i ant*.deb
              # https://github.com/actions/checkout
              - name: Checkout codebase
                uses: actions/checkout@v3
              # https://github.com/actions/cache
              - name: Cache Maven dependencies
                uses: actions/cache@v3
                with:
                  # Cache entire ~/.m2/repository
                  path: /root/.m2/repository
                  # Cache key is hash of all pom.xml files. Therefore any changes to POMs will invalidate cache
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-maven-
              # deploy needs various postgres cli tools
              - name: info
                run: ci/info.sh
              - name: deploy
                run: ci/build.sh
              - name: test
                run: ci/test.sh
